services:
  - type: web
    name: aditya-l1-solar-warning-api
    env: python
    buildCommand: pip install -r requirements.txt fastapi uvicorn pydantic && python generate_sample_data.py && python train.py
    startCommand: uvicorn api:app --host 0.0.0.0 --port $PORT
    plan: free
    region: oregon
